### PR TITLE
loosen superb description RegExp - fixes #59

### LINKED ISSUE #59: Hyphenated or punctuated superb descriptions cause test to fail
As pointed out by @JonnyBurger in [PR #58](https://github.com/sindresorhus/generator-nm/pull/58), there is a small chance (~5%) that the `RegExp` in the [unit tests for the prompt description](https://github.com/sindresorhus/generator-nm/blob/master/test.js#L136-L137):

```js
"My (\w)+ module"
``` 
might cause the test to fail on spaced, hyphenated or punctuated superb values like:

```
"awe-inspiring",
"bee's knees",
"cat's pajamas",
```
So I propose a slightly more generic, and forgiving RegExp like:

```js
/My (.)+ module/
```

Which would future-proof itself to any other entries to the superb module that might involve punctuation or multiple words.

### PR DESCRIPTION
**Pull request by radiovisual**

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -133,6 +133,6 @@ test.serial('defaults to superb description', async () => {
 
 	await pify(generator.run.bind(generator))();
 
-	assert.fileContent('package.json', /"description": "My (\w)+ module",/);
-	assert.fileContent('readme.md', /> My (\w)+ module/);
+	assert.fileContent('package.json', /"description": "My (.)+ module",/);
+	assert.fileContent('readme.md', /> My (.)+ module/);
```
Comment (sindresorhus) [inline test.js]: Actually, you don't need the parens. You're not capturing anything here.

**Comment by sindresorhus** [comment]
👌
